export enum LoginActionsTypes {
  GET_LOGIN = 'GET_LOGIN',
  GET_LOGIN_FAIL = 'GET_LOGIN_FAIL',
  GET_LOGIN_ATTEMPT = 'GET_LOGIN_ATTEMPT',
  GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS',
  RESET_LOGIN = 'RESET_LOGIN',

  LOGIN_EMAIL_REQUESTED = 'LOGIN_EMAIL_REQUESTED',
  LOGIN_EMAIL_FAILED = 'LOGIN_EMAIL_FAILED',
  LOGIN_EMAIL_SUCCEEDED = 'LOGIN_EMAIL_SUCCEEDED',
}
