import {StyleSheet} from "react-native";
import colors from "../../constants/Colors";
import {width, height} from "../../constants/Layout";

const styles = StyleSheet.create({
    backgroundView: {},
    centeredView: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 22,
        backgroundColor: "rgba(0,0,0,0.8)",
    },
    modalView: {
        width: width - 10,
        height: height - 100,
        margin: 20,
        backgroundColor: "white",
        borderRadius: 20,
        padding: 35,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    avatarView: {
        height: 300,
        width: 220,
    },
    avatarLeft: {
        position: "absolute",
        left: 0,
        bottom: 0,
        height: height / 3,
        width: width / 3,
        transform: [{rotate: "-15deg"}],
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowOpacity: 0.46,
        shadowRadius: 11.14,
    },
    avatarRight: {
        zIndex: -1,
        position: "absolute",
        right: 0,
        top: 0,
        height: height / 3,
        width: width / 3,
        transform: [{rotate: "8deg"}],
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowOpacity: 0.46,
        shadowRadius: 11.14,
    },
    iconLeft: {
        position: "absolute",
        zIndex: 1,
        backgroundColor: "#fff",
        borderRadius: 25,
        alignItems: "center",
        justifyContent: "center",
        width: 40,
        height: 40,
        bottom: -10,
        left: -10,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowOpacity: 0.46,
        shadowRadius: 11.14,
    },
    iconRight: {
        position: "absolute",
        zIndex: 1,
        backgroundColor: "#fff",
        borderRadius: 25,
        alignItems: "center",
        justifyContent: "center",
        width: 40,
        height: 40,
        top: -10,
        left: -10,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowOpacity: 0.46,
        shadowRadius: 11.14,
    },
    matchedText: {
        marginTop: 50,
        alignItems: "center",
    },
    textTitle: {
        color: colors.redColor,
        fontSize: 24,
        marginBottom: 10,
    },
    button: {
        borderRadius: 20,
        padding: 10,
        elevation: 2,
        marginTop: 10,
        width: width - 100,
        alignItems: "center",
    },
    textStyle: {
        color: "white",
        fontWeight: "bold",
        textAlign: "center",
    },
    textSayHello: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    buttonSayHello: {
        fontStyle: "italic",
        fontWeight: "bold",
        backgroundColor: colors.redColor,
    },
    textHideModal: {
        color: colors.redColor,
        fontSize: 16,
        fontWeight: "bold",
    },
    buttonHideModal: {
        fontStyle: "italic",
        fontWeight: "bold",
        backgroundColor: colors.redOpacityColor,
    },
});

export default styles;
